# Predicting real estate prices - Model serving and deployment

## Background
Sound Realty helps people sell homes in the Seattle area.

They currently spend too much time and effort on estimating the value of properties.

One of their staff has heard a lot about machine learning (ML) and has created a basic model to estimate the value of properties.

The basic model uses only numeric variables and ignores some other attributes.
Despite the simplicity of this model, the folks at Sound are impressed with the proof of concept and would now like to use this model to streamline
their business.

They have contracted us to help deploy that model for broader use.
Our job is to create a REST endpoint that serves up model predictions for new data, and to provide guidance on how they could improve the model.

## Proposed Solution

Here I shall deploy the model to a REST endpoint using Modal.

## Library Installation and Import

Below I shall install then import the libraries needed.

In [2]:
!pip install uv

Collecting uv
  Downloading uv-0.8.19-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Downloading uv-0.8.19-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 2.8 MB/s eta 0:00:0000:0100:01
Installing collected packages: uv
Successfully installed uv-0.8.19

In [80]:
#%pip install seaborn tqdm sweetviz dash streamlit plotly requests gradio joblib scikit-learn ipywidgets modal bentoml wandb

In [1]:
%uv pip install seaborn tqdm sweetviz dash streamlit plotly requests gradio
%uv pip install joblib scikit-learn ipywidgets modal bentoml wandb

Using Python 3.10.12 environment at: /usr
Resolved 96 packages in 2.68s
Prepared 6 packages in 24.58s
error: Failed to install: pyparsing-3.2.5-py3-none-any.whl (pyparsing==3.2.5)
  Caused by: failed to create directory `/usr/local/lib/python3.10/dist-packages/pyparsing-3.2.5.dist-info`: Permission denied (os error 13)
Note: you may need to restart the kernel to use updated packages.
Using Python 3.10.12 environment at: /usr
Resolved 117 packages in 2.09s
Prepared 5 packages in 3.45s
error: Failed to install: threadpoolctl-3.6.0-py3-none-any.whl (threadpoolctl==3.6.0)
  Caused by: failed to create directory `/usr/local/lib/python3.10/dist-packages/threadpoolctl-3.6.0.dist-info`: Permission denied (os error 13)
Note: you may need to restart the kernel to use updated packages.

### Imports

In [9]:
import pandas as pd, matplotlib.pyplot as plt, seaborn as sns, numpy as np
from numpy import random
from tqdm import tqdm
from ipywidgets import interact
from pathlib import Path
import os, warnings, io, getpass, json, dash, modal, bentoml, gc, wandb, pickle
from joblib import dump, load
from dash import dcc, html, dash_table
import typing as t
from bentoml.validators import DataframeSchema
np.set_printoptions(linewidth=130)
plt.rc('image', cmap='Greys')
import sys

## Exploratory Data Analysis

We have 3 datasets namely
- **kc_house_data.csv** – Data for training the model
- **zipcode_demographics.csv** – Additional demographic data from the U.S. Census which are used as features. This data should be joined to the primary home sales using the zipcode column.
- **future_unseen_examples.csv** – This file contains examples of homes to be sold in the future. It includes all attributes from the original home sales file, but not the price , date , or id . It also does not include the demographic data.


Lets first take a look at our dataset

In [3]:
path = Path('..')
path

PosixPath('..')

In [4]:
!ls ../data

future_unseen_examples.csv  kc_house_data.csv  zipcode_demographics.csv

In [10]:
train_df = pd.read_csv(path/'data/kc_house_data.csv', index_col='id')
demographics_df = pd.read_csv(path/'data/zipcode_demographics.csv')
test_df = pd.read_csv(path/'data/future_unseen_examples.csv')

In [11]:
train_df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [12]:
#train_df??

In [8]:
train_df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [15]:
test_df.columns

Index(['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [16]:
demographics_df.columns

Index(['ppltn_qty', 'urbn_ppltn_qty', 'sbrbn_ppltn_qty', 'farm_ppltn_qty',
       'non_farm_qty', 'medn_hshld_incm_amt', 'medn_incm_per_prsn_amt',
       'hous_val_amt', 'edctn_less_than_9_qty', 'edctn_9_12_qty',
       'edctn_high_schl_qty', 'edctn_some_clg_qty', 'edctn_assoc_dgre_qty',
       'edctn_bchlr_dgre_qty', 'edctn_prfsnl_qty', 'per_urbn', 'per_sbrbn',
       'per_farm', 'per_non_farm', 'per_less_than_9', 'per_9_to_12', 'per_hsd',
       'per_some_clg', 'per_assoc', 'per_bchlr', 'per_prfsnl', 'zipcode'],
      dtype='object')

In [17]:
!ls ../model

model.pkl  model_features.json

In [18]:
import json
from pathlib import Path

# Check different possible locations
possible_paths = [
    Path("model_features.json"),  # current directory
    Path("model/model_features.json"),  # model subdirectory
    Path("../model/model_features.json"),  # parent directory
    Path("data/model_features.json"),  # data directory if you have one
]

for path in possible_paths:
    if path.exists():
        print(f"Found features file at: {path}")
        model_features = json.loads(path.read_text())
        print("Model features:", model_features)
        break
else:
    print("model_features.json not found in any expected location")

Found features file at: ../model/model_features.json
Model features: ['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'sqft_above', 'sqft_basement', 'ppltn_qty', 'urbn_ppltn_qty', 'sbrbn_ppltn_qty', 'farm_ppltn_qty', 'non_farm_qty', 'medn_hshld_incm_amt', 'medn_incm_per_prsn_amt', 'hous_val_amt', 'edctn_less_than_9_qty', 'edctn_9_12_qty', 'edctn_high_schl_qty', 'edctn_some_clg_qty', 'edctn_assoc_dgre_qty', 'edctn_bchlr_dgre_qty', 'edctn_prfsnl_qty', 'per_urbn', 'per_sbrbn', 'per_farm', 'per_non_farm', 'per_less_than_9', 'per_9_to_12', 'per_hsd', 'per_some_clg', 'per_assoc', 'per_bchlr', 'per_prfsnl']

In [37]:
len(train_df.columns),len(test_df.columns)

(20, 18)

In [23]:
demographics_df

,ppltn_qty,urbn_ppltn_qty,sbrbn_ppltn_qty,farm_ppltn_qty,non_farm_qty,medn_hshld_incm_amt,medn_incm_per_prsn_amt,hous_val_amt,edctn_less_than_9_qty,edctn_9_12_qty,...,per_farm,per_non_farm,per_less_than_9,per_9_to_12,per_hsd,per_some_clg,per_assoc,per_bchlr,per_prfsnl,zipcode
0,38249.0,37394.0,0.0,0.0,855.0,66051.0,25219.0,192000.0,437.0,2301.0,...,0.0,2.0,1.0,6.0,18.0,20.0,5.0,12.0,4.0,98042
1,22036.0,22036.0,0.0,0.0,0.0,91904.0,53799.0,573900.0,149.0,404.0,...,0.0,0.0,0.0,1.0,6.0,12.0,3.0,27.0,22.0,98040
2,18194.0,18194.0,0.0,0.0,0.0,61813.0,31765.0,246600.0,269.0,905.0,...,0.0,0.0,1.0,4.0,13.0,20.0,6.0,19.0,9.0,98028
3,21956.0,21956.0,0.0,0.0,0.0,47461.0,22158.0,175400.0,925.0,1773.0,...,0.0,0.0,4.0,8.0,20.0,21.0,5.0,12.0,4.0,98178
4,22814.0,22814.0,0.0,0.0,0.0,48606.0,28398.0,252600.0,599.0,1148.0,...,0.0,0.0,2.0,5.0,13.0,17.0,5.0,23.0,12.0,98007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,35140.0,35021.0,0.0,0.0,119.0,81929.0,41856.0,335900.0,212.0,865.0,...,0.0,0.0,0.0,2.0,8.0,15.0,4.0,27.0,15.0,98006
66,23926.5,23298.0,0.0,0.0,0.0,56933.0,27639.5,239850.0,406.0,1213.0,...,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5,98074
67,23926.5,23298.0,0.0,0.0,0.0,56933.0,27639.5,239850.0,406.0,1213.0,...,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5,98077
68,23926.5,23298.0,0.0,0.0,0.0,56933.0,27639.5,239850.0,406.0,1213.0,...,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5,98030
69,23926.5,23298.0,0.0,0.0,0.0,56933.0,27639.5,239850.0,406.0,1213.0,...,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5,98075

In [24]:
test_df

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,4,1.00,1680,5043,1.5,0,0,4,6,1680,0,1911,0,98118,47.5354,-122.273,1560,5765
1,3,2.50,2220,6380,1.5,0,0,4,8,1660,560,1931,0,98115,47.6974,-122.313,950,6380
2,3,2.25,1630,10962,1.0,0,0,4,8,1100,530,1977,0,98030,47.3801,-122.166,1830,8470
3,5,2.50,1710,9720,2.0,0,0,4,8,1710,0,1974,0,98005,47.5903,-122.157,2270,9672
4,2,1.00,850,6370,1.0,0,0,3,6,850,0,1951,0,98126,47.5198,-122.373,850,5170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3,2.50,2430,54059,2.0,0,0,3,10,2430,0,1987,0,98027,47.4664,-121.992,2910,49658
96,2,2.50,1240,1249,3.0,0,0,3,8,1240,0,2006,0,98107,47.6718,-122.386,1240,2500
97,4,1.75,1860,9750,1.0,0,0,3,7,1460,400,1969,0,98034,47.7097,-122.202,1900,8913
98,5,1.75,2330,3800,1.5,0,0,3,7,1360,970,1927,0,98115,47.6835,-122.308,2100,3800
99,4,2.50,2550,4630,2.0,0,0,3,7,2550,0,2005,0,98075,47.5928,-122.004,2550,5151

In [26]:
!ls model

model.pkl  model_features.json

In [13]:
model_path = path/'model/model.pkl'

In [14]:
if os.path.exists(model_path):
           print(f"Loading existing model from pickle at {model_path}")
           with open(model_path, 'rb') as f:
               model = pickle.load(f)
           print(model)

Loading existing model from pickle at ../model/model.pkl

/home/rubanza/.local/lib/python3.10/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator RobustScaler from version 1.7.2 when using version 1.3.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

Pipeline(steps=[('robustscaler', RobustScaler()),
                ('kneighborsregressor', KNeighborsRegressor())])

/home/rubanza/.local/lib/python3.10/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator KNeighborsRegressor from version 1.7.2 when using version 1.3.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/home/rubanza/.local/lib/python3.10/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator Pipeline from version 1.7.2 when using version 1.3.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [15]:
def load_model(model_path="../model/model.pkl"):
    """
    Function to load the model

    Args
    model_path: the path to the model
    """
    if os.path.exists(model_path):
        print(f"Loading existing model from pickle at {model_path}")
        with open(model_path, 'rb') as f:
            model = pickle.load(f)
        return model
    else:
        print(f"Model file not found at {model_path}")
        return None

In [22]:
load_model

In [23]:
load_model??

Signature: load_model(model_path='model/model.pkl')
Source:
def load_model(model_path="model/model.pkl"):
    """
    Function to load the model

    Args
    model_path: the path to the model
    """
    if os.path.exists(model_path):
        print(f"Loading existing model from pickle at {model_path}")
        with open(model_path, 'rb') as f:
            model = pickle.load(f)
        return model
    else:
        print(f"Model file not found at {model_path}")
        return None
File:      /tmp/ipykernel_100471/1537687095.py
Type:      function

In [16]:
model = load_model()
model

Loading existing model from pickle at ../model/model.pkl

Pipeline(steps=[('robustscaler', RobustScaler()),
                ('kneighborsregressor', KNeighborsRegressor())])

In [41]:
#model.predict(test_df)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- condition
- grade
- lat
- long
- sqft_living15
- ...
Feature names seen at fit time, yet now missing:
- edctn_9_12_qty
- edctn_assoc_dgre_qty
- edctn_bchlr_dgre_qty
- edctn_high_schl_qty
- edctn_less_than_9_qty
- ...

## Trial solution 1 - chatgpt

In [17]:
import pandas as pd
import numpy as np

# --------------------------
# Example: model_expected list
# --------------------------
model_expected = [
    'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
    'sqft_above', 'sqft_basement',
    'ppltn_qty', 'urbn_ppltn_qty', 'sbrbn_ppltn_qty', 'farm_ppltn_qty', 'non_farm_qty',
    'medn_hshld_incm_amt', 'medn_incm_per_prsn_amt', 'hous_val_amt',
    'edctn_less_than_9_qty', 'edctn_9_12_qty', 'edctn_high_schl_qty', 'edctn_some_clg_qty',
    'edctn_assoc_dgre_qty', 'edctn_bchlr_dgre_qty', 'edctn_prfsnl_qty',
    'per_urbn', 'per_sbrbn', 'per_farm', 'per_non_farm',
    'per_less_than_9', 'per_9_to_12', 'per_hsd', 'per_some_clg',
    'per_assoc', 'per_bchlr', 'per_prfsnl'
]

# --------------------------
# 1. Merge housing with demographics
# --------------------------
# Ensure zipcodes are the same dtype (string recommended to preserve leading zeros)
test_df['zipcode'] = test_df['zipcode'].astype(str)
demographics_df['zipcode'] = demographics_df['zipcode'].astype(str)

# Merge on zipcode
inference_df = test_df.merge(demographics_df, on='zipcode', how='left')
inference_df

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,...,per_sbrbn,per_farm,per_non_farm,per_less_than_9,per_9_to_12,per_hsd,per_some_clg,per_assoc,per_bchlr,per_prfsnl
0,4,1.00,1680,5043,1.5,0,0,4,6,1680,...,0.0,0.0,0.0,9.0,9.0,17.0,15.0,4.0,11.0,6.0
1,3,2.50,2220,6380,1.5,0,0,4,8,1660,...,0.0,0.0,0.0,0.0,2.0,8.0,15.0,4.0,30.0,20.0
2,3,2.25,1630,10962,1.0,0,0,4,8,1100,...,0.0,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5
3,5,2.50,1710,9720,2.0,0,0,4,8,1710,...,0.0,0.0,0.0,2.0,3.0,10.0,17.0,4.0,26.0,16.0
4,2,1.00,850,6370,1.0,0,0,3,6,850,...,0.0,0.0,0.0,4.0,7.0,16.0,19.0,5.0,16.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3,2.50,2430,54059,2.0,0,0,3,10,2430,...,0.0,0.0,19.0,1.0,3.0,12.0,17.0,6.0,24.0,11.0
96,2,2.50,1240,1249,3.0,0,0,3,8,1240,...,0.0,0.0,0.0,1.0,5.0,14.0,20.0,5.0,28.0,11.0
97,4,1.75,1860,9750,1.0,0,0,3,7,1460,...,0.0,0.0,0.0,1.0,4.0,14.0,21.0,6.0,20.0,8.0
98,5,1.75,2330,3800,1.5,0,0,3,7,1360,...,0.0,0.0,0.0,0.0,2.0,8.0,15.0,4.0,30.0,20.0
99,4,2.50,2550,4630,2.0,0,0,3,7,2550,...,0.0,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5

In [18]:
test_df.shape,demographics_df.shape,inference_df.shape

((100, 18), (70, 27), (100, 44))

In [19]:
inference_df.columns

Index(['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15', 'ppltn_qty', 'urbn_ppltn_qty',
       'sbrbn_ppltn_qty', 'farm_ppltn_qty', 'non_farm_qty',
       'medn_hshld_incm_amt', 'medn_incm_per_prsn_amt', 'hous_val_amt',
       'edctn_less_than_9_qty', 'edctn_9_12_qty', 'edctn_high_schl_qty',
       'edctn_some_clg_qty', 'edctn_assoc_dgre_qty', 'edctn_bchlr_dgre_qty',
       'edctn_prfsnl_qty', 'per_urbn', 'per_sbrbn', 'per_farm', 'per_non_farm',
       'per_less_than_9', 'per_9_to_12', 'per_hsd', 'per_some_clg',
       'per_assoc', 'per_bchlr', 'per_prfsnl'],
      dtype='object')

In [20]:

# --------------------------
# 2. Check coverage of expected features
# --------------------------
missing_features = set(model_expected) - set(inference_df.columns)
if missing_features:
    print("WARNING: These expected features are missing after merge:", missing_features)
else:
    print("All expected features are present after merge.")

All expected features are present after merge.

In [21]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   bedrooms       100 non-null    int64
 1   bathrooms      100 non-null    float64
 2   sqft_living    100 non-null    int64
 3   sqft_lot       100 non-null    int64
 4   floors         100 non-null    float64
 5   waterfront     100 non-null    int64
 6   view           100 non-null    int64
 7   condition      100 non-null    int64
 8   grade          100 non-null    int64
 9   sqft_above     100 non-null    int64
 10  sqft_basement  100 non-null    int64
 11  yr_built       100 non-null    int64
 12  yr_renovated   100 non-null    int64
 13  zipcode        100 non-null    object
 14  lat            100 non-null    float64
 15  long           100 non-null    float64
 16  sqft_living15  100 non-null    int64
 17  sqft_lot15     100 non-null    int64
dtypes: float64(4), int64(13), object(1)
memory usage: 14.2+ KB

In [22]:
test_df.isnull().sum()

bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [23]:

# --------------------------
# 3. Impute missing values (basic strategy: median imputation)
# --------------------------
# (In production you should use the exact imputation strategy/scaler from training.)
for col in model_expected:
    if inference_df[col].isnull().any():
        median_val = inference_df[col].median()
        inference_df[col] = inference_df[col].fillna(median_val)
        print(f"Filled NaNs in {col} with median {median_val}")

In [24]:

# --------------------------
# 4. Reorder columns to match model input order
# --------------------------
inference_df = inference_df[model_expected]
inference_df

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,sqft_above,sqft_basement,ppltn_qty,urbn_ppltn_qty,sbrbn_ppltn_qty,...,per_sbrbn,per_farm,per_non_farm,per_less_than_9,per_9_to_12,per_hsd,per_some_clg,per_assoc,per_bchlr,per_prfsnl
0,4,1.00,1680,5043,1.5,1680,0,40409.0,40409.0,0.0,...,0.0,0.0,0.0,9.0,9.0,17.0,15.0,4.0,11.0,6.0
1,3,2.50,2220,6380,1.5,1660,560,43263.0,43263.0,0.0,...,0.0,0.0,0.0,0.0,2.0,8.0,15.0,4.0,30.0,20.0
2,3,2.25,1630,10962,1.0,1100,530,23926.5,23298.0,0.0,...,0.0,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5
3,5,2.50,1710,9720,2.0,1710,0,17150.0,17150.0,0.0,...,0.0,0.0,0.0,2.0,3.0,10.0,17.0,4.0,26.0,16.0
4,2,1.00,850,6370,1.0,850,0,19435.0,19435.0,0.0,...,0.0,0.0,0.0,4.0,7.0,16.0,19.0,5.0,16.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3,2.50,2430,54059,2.0,2430,0,22271.0,18009.0,0.0,...,0.0,0.0,19.0,1.0,3.0,12.0,17.0,6.0,24.0,11.0
96,2,2.50,1240,1249,3.0,1240,0,18314.0,18314.0,0.0,...,0.0,0.0,0.0,1.0,5.0,14.0,20.0,5.0,28.0,11.0
97,4,1.75,1860,9750,1.0,1460,400,40127.0,40127.0,0.0,...,0.0,0.0,0.0,1.0,4.0,14.0,21.0,6.0,20.0,8.0
98,5,1.75,2330,3800,1.5,1360,970,43263.0,43263.0,0.0,...,0.0,0.0,0.0,0.0,2.0,8.0,15.0,4.0,30.0,20.0
99,4,2.50,2550,4630,2.0,2550,0,23926.5,23298.0,0.0,...,0.0,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5

### How reodering works

In [25]:
# --------------------------
# 4. Reorder columns to match model input order
# --------------------------
inference_df_d = test_df.merge(demographics_df, on='zipcode', how='left').copy()
inference_df_a = inference_df_d.copy()
inference_df_b = inference_df_a[['bedrooms','floors','zipcode']]
inference_df_b

    bedrooms  floors zipcode
0          4     1.5   98118
1          3     1.5   98115
2          3     1.0   98030
3          5     2.0   98005
4          2     1.0   98126
..       ...     ...     ...
95         3     2.0   98027
96         2     3.0   98107
97         4     1.0   98034
98         5     1.5   98115
99         4     2.0   98075

[100 rows x 3 columns]

In [26]:
# --------------------------
# 5. Type consistency: ensure all numeric
# --------------------------
#inference_df = inference_df.apply(pd.to_numeric, errors='coerce')

# --------------------------
# 6. Final sanity checks
# --------------------------
print("Final shape:", inference_df.shape)
print("Any NaNs left?", inference_df.isna().any().any())

# Now you can feed inference_df into your trained model:
# preds = model.predict(inference_df)

Final shape: (100, 33)
Any NaNs left? False

In [27]:
inference_df.isna().any().any()

False

In [28]:
predictions = model.predict(inference_df)
predictions.shape

(100,)

In [29]:
predictions

array([ 458520. ,  612800. ,  449160. ,  679700. ,  304256. ,  553798. ,  341800. ,  445350. ,  990500. ,  532940. ,  422700. ,
        484220. ,  499400. ,  358470. ,  790700. ,  236300. ,  426950. ,  687600. ,  619880. ,  438000. ,  520800. ,  669300.2,
        549036. ,  411100. ,  250190. ,  313590. ,  730800. ,  285730. ,  256990. ,  390200. ,  285942.4,  865700. ,  975500. ,
        494936. ,  272090. ,  297900. ,  302298. ,  612000. ,  222590. ,  297940. ,  213800. ,  796988. ,  407260. ,  307300. ,
        451000. ,  263660. ,  297560. ,  658200. ,  261500. ,  288890. , 1241796. ,  279380. ,  252390. ,  252980. ,  569370. ,
        524790. ,  602670. ,  427900. ,  406000. ,  890000. ,  486090. ,  317402. ,  886700. ,  421650. ,  321999. ,  390360. ,
        486980. ,  499000. ,  344200. ,  558650. ,  264590. ,  711190. ,  259930. ,  614000. ,  424089.8,  522800. ,  520300. ,
        412600. ,  830000. ,  258906. ,  726500. ,  565600. ,  220941.6,  404500. ,  412002.8,  795932. ,  184300. ,  562750. ,
        540614. ,  364400. ,  242000. ,  644200. ,  272200. ,  500990. ,  831690. ,  535800. ,  452800. ,  471817. ,  609388. ,
        573300. ])

In [30]:
inference_df_c = inference_df.copy()
inference_df_c.shape

(100, 33)

In [31]:
preds = model.predict(inference_df_c)
inference_df_c["predicted_price"] = preds
inference_df_c.to_csv("predictions.csv", index=False)
print("Predictions written to predictions.csv")

Predictions written to predictions.csv

In [32]:
!ls

predictions.csv  sound_realty.ipynb

In [33]:
sub_df = pd.read_csv('predictions.csv')
sub_df

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,sqft_above,sqft_basement,ppltn_qty,urbn_ppltn_qty,sbrbn_ppltn_qty,...,per_farm,per_non_farm,per_less_than_9,per_9_to_12,per_hsd,per_some_clg,per_assoc,per_bchlr,per_prfsnl,predicted_price
0,4,1.00,1680,5043,1.5,1680,0,40409.0,40409.0,0.0,...,0.0,0.0,9.0,9.0,17.0,15.0,4.0,11.0,6.0,458520.0
1,3,2.50,2220,6380,1.5,1660,560,43263.0,43263.0,0.0,...,0.0,0.0,0.0,2.0,8.0,15.0,4.0,30.0,20.0,612800.0
2,3,2.25,1630,10962,1.0,1100,530,23926.5,23298.0,0.0,...,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5,449160.0
3,5,2.50,1710,9720,2.0,1710,0,17150.0,17150.0,0.0,...,0.0,0.0,2.0,3.0,10.0,17.0,4.0,26.0,16.0,679700.0
4,2,1.00,850,6370,1.0,850,0,19435.0,19435.0,0.0,...,0.0,0.0,4.0,7.0,16.0,19.0,5.0,16.0,7.0,304256.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3,2.50,2430,54059,2.0,2430,0,22271.0,18009.0,0.0,...,0.0,19.0,1.0,3.0,12.0,17.0,6.0,24.0,11.0,535800.0
96,2,2.50,1240,1249,3.0,1240,0,18314.0,18314.0,0.0,...,0.0,0.0,1.0,5.0,14.0,20.0,5.0,28.0,11.0,452800.0
97,4,1.75,1860,9750,1.0,1460,400,40127.0,40127.0,0.0,...,0.0,0.0,1.0,4.0,14.0,21.0,6.0,20.0,8.0,471817.0
98,5,1.75,2330,3800,1.5,1360,970,43263.0,43263.0,0.0,...,0.0,0.0,0.0,2.0,8.0,15.0,4.0,30.0,20.0,609388.0
99,4,2.50,2550,4630,2.0,2550,0,23926.5,23298.0,0.0,...,0.0,0.0,1.0,5.0,15.0,19.0,5.0,19.0,7.5,573300.0

In [35]:
!ls ../data

future_unseen_examples.csv  kc_house_data.csv  zipcode_demographics.csv

In [ ]:
#eos

## API 

We are now going to start by uploading our data to modal using volumes. To quote the modal documentation

Modal Volumes provide a high-performance distributed file system for your modal applications. They are designed for write-once, read-many I/O workloads, like creating machine learning model weights and distributing them for inference.

Uploading our data will enable our training function that we run later to access the data it will need to train our machine learning model.

In [36]:
!modal setup

Was not able to launch web browsere web browserer
Please go to this URL manually and complete the flow:

]8;id=677808;https://modal.com/token-flow/tf-k8kvOlYMnC5KNQ7k4SsDwU\https://modal.com/token-flow/tf-k8kvOlYMnC5KNQ7k4SsDwU]8;;\

⠹ Waiting for authentication in the web browser
⠙ Waiting for token flow to complete... (attempt 2)
Web authentication finished successfully!
Token is connected to the flexible-functions-ai workspace.
Verifying token against https://api.modal.com
Token verified successfully!
⠋ Storing token
Token written to /home/rubanza/.modal.toml in profile flexible-functions-ai.

## Data Upload

In [56]:
!ls ../data

future_unseen_examples.csv  kc_house_data.csv  zipcode_demographics.csv

In [47]:
!python ../data_upload.py ../data

In [ ]:
python data_upload.py ./data

In [65]:
from modal import App, Volume, Mount
from pathlib import Path
import shutil, os

app = App("sr-data-upload")

volume = Volume.from_name("sr-data-volume", create_if_missing=True)

# Mount local ../data into the container at /source_data
local_mount = Mount.from_local_dir("../data", remote_path="/source_data")

@app.function(volumes={"/data": volume}, mounts=[local_mount])
def upload_data():
    os.makedirs("/data", exist_ok=True)

    for file in Path("/source_data").glob("*"):
        dest = f"/data/{file.name}"
        if file.is_file():
            shutil.copy(file, dest)
            print(f"Copied {file} to {dest}")

    print("\nFiles in Modal volume:")
    for file in Path("/data").glob("*"):
        print(f" - {file}")

with app.run():
    upload_data.remote()

/tmp/ipykernel_286169/1567640505.py:10: DeprecationError: 2025-01-08: modal.Mount usage will soon be deprecated.

Use image.add_local_dir instead, which is functionally and performance-wise equivalent.

See https://modal.com/docs/guide/modal-1-0-migration for more details.

  local_mount = Mount.from_local_dir("../data", remote_path="/source_data")

In [66]:
from modal import App, Volume, Mount
from pathlib import Path
import shutil, os

# Define Modal app
app = App("sr2-data-upload")

# Persistent Modal volume
volume = Volume.from_name("sr2-data-volume", create_if_missing=True)

# Mount local ../data into the container at /source_data
local_mount = Mount.from_local_dir("../data", remote_path="/source_data")

# Function that runs inside Modal container
@app.function(volumes={"/data": volume}, mounts=[local_mount])
def upload_data():
    os.makedirs("/data", exist_ok=True)

    # Copy files from mounted dir into the volume
    for file in Path("/source_data").glob("*"):
        dest = f"/data/{file.name}"
        if file.is_file():
            shutil.copy(file, dest)
            print(f"Copied {file} to {dest}")

    # Confirm files in the volume
    print("\nFiles in Modal volume:")
    for file in Path("/data").glob("*"):
        print(f" - {file}")

# Run the app inside the notebook
with app.run():
    upload_data.remote()

/tmp/ipykernel_286169/3241485202.py:12: DeprecationError: 2025-01-08: modal.Mount usage will soon be deprecated.

Use image.add_local_dir instead, which is functionally and performance-wise equivalent.

See https://modal.com/docs/guide/modal-1-0-migration for more details.

  local_mount = Mount.from_local_dir("../data", remote_path="/source_data")

In [68]:
from modal import App, Volume, Image
from pathlib import Path
import shutil, os

# Define Modal app
app = App("sr3-data-upload")

# Persistent Modal volume
volume = Volume.from_name("sr3-data-volume", create_if_missing=True)

# Define an image with your local ../data added at /source_data
image = Image.debian_slim().add_local_dir("../data", "/source_data")

# Function that runs inside Modal container
@app.function(volumes={"/data": volume}, image=image)
def upload_data():
    os.makedirs("/data", exist_ok=True)

    # Copy files from baked-in /source_data into the persistent volume
    for file in Path("/source_data").glob("*"):
        dest = f"/data/{file.name}"
        if file.is_file():
            shutil.copy(file, dest)
            print(f"Copied {file} to {dest}")

    # Confirm files in the volume
    print("\nFiles in Modal volume:")
    for file in Path("/data").glob("*"):
        print(f" - {file}")

# Run the app inside the notebook
with app.run():
    upload_data.remote()